### ISSUE TITLE
Admin panel Table Headers are removed when "Next" button is pressed

### ISSUE THREAD

**Issue by mmetro** [mmetro/WeirdSideofYouTube#30]
The headers for the table on the admin panel are removed when the next page of videos is loaded.

**Comment by youngcc3157** [comment]
fixed this on the website by simply changing "$('#videoTable tr').remove();" into "$('#videoTable td').remove();" since every time we click Next or Previous we remove everything in the table instead of removing only elements in td.

**Comment by mmetro** [comment]
I think we need to remove the <tr> tags, because the browser keeps adding more and more <tr> every time you load the next page.  I think what we need to do is remove the <tr> and then add back the header row.

We could also traverse the DOM to only remove <tr> that contains <td>.  We would want to go to the <td> in the table, then go up one level to the <tr>, and remove the <tr>.  Rinse and repeat until we don't find any more <td>

**Comment by mmetro** [comment]
Fixed by creating a class for the video rows, and only removing those <tr>
