### ISSUE TITLE
Web design improved and finalized

### ISSUE THREAD

**Issue by mmetro** [mmetro/WeirdSideofYouTube#52]

**Comment by Bad-Science** [comment]
Please add some detail here. What elements need improvement? How should they be improved?

**Comment by siviyn** [comment]
Want to fix how the text looks when you have the site open in a smaller window, the text wraps on the second line and writes over the first line of text. This mostly applies to the history and admin page. I also want to update the about page to include an "In honor of" part for Mike with a picture and some words.

**Comment by jemzlee** [comment]
Should be an easy fix. I think html has a scaleable

**Comment by jemzlee** [comment]
Should be an easy fix. Html has a scalable option for font sizes depending on the window. We'll discuss what the "In honor of" part for Mike will look like.

**Comment by siviyn** [comment]
I got the licensed composite picture of Mike from Tasty with the copyright so we can use that whenever we want to put that up.

**Comment by siviyn** [comment]
The current issue for front end is the navbar. I have a pure css model for what I want to replace our navbar with it but I haven't had the time to do so. Next week I'll have the navbar in place and this issue should be closed.

**Comment by siviyn** [comment]
Finished.
