### ISSUE TITLE
Unify coding style

### ISSUE THREAD

**Issue by mmetro** [mmetro/WeirdSideofYouTube#56]
At the minimum, we should determine a standard indentation style, and make all files adhere to it.

**Comment by mmetro** [comment]
I'm in favor of indenting by two spaces.

**Comment by jemzlee** [comment]
I'm down for 2 spaces. It's a simple thing to edit in the editor.

**Comment by siviyn** [comment]
Yea two spaces sounds fine

**Comment by colatkinson** [comment]
We could use [ESLint](http://eslint.org) to check style automatically. It can also integrate with Atom, Sublime, etc. so it's super easy to use.
