### ISSUE TITLE
Remap skip controls

### ISSUE THREAD

**Issue by mmetro** [mmetro/WeirdSideofYouTube#9]
Using the arrow keys to skip videos goes against the well-established use of the arrow keys for advancing the video.  It should be remapped to a different key, or a button could be made

**Comment by jacobjiggler** [comment]
When you enter the scope of the video(having clicked it), the keys should still act as skips on the video without changing the video, but when you're not in the scope of the video, it will change the video. The alternative is you press the arrow keys and it does nothing, if you havent yet clicked the video.
